# Generated by Django 3.0.2 on 2020-01-18 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='mentor',
            field=models.TextField(default='ayush'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='room',
            name='startup',
            field=models.TextField(default='ayush'),
            preserve_default=False,
        ),
    ]
